language: go
dist: bionic
sudo: required

go:
  - 1.14.x


before_install:
  - sudo apt-get -y install kea-dhcp4-server
  - sudo apt-get -y install kea-dhcp6-server
  - go get -t -v ./...
  

script: |
  sudo -E env "PATH=$PATH" go test -v 


